### ISSUE TITLE
Retorno do status da fatura

### ISSUE THREAD

**Issue by willmkt** [mja-maia/gerador-fatura-IUGU#1]
Cara segui seu exemplo e funcionou, mas agora estou tentando retornar o status do pagamento da fatura, e não deu certo.

Você ja implementou isso?
Tem algum exemplo?

Valeu.

**Comment by cupdev** [comment]
Como assim? Pode explicar um pouco melhor?

**Comment by willmkt** [comment]
Quando criar a fatura passar notification_url, e depois receber os dados para alterar o status da fatura.

**Comment by mja-maia** [comment]
Receber os dados da fatura, para depois conseguir atualiza-la? Teria que usar um webhook da IUGU. Vou implementar isso, é uma boa ideia.  Depois me passe seu email se possível. ;)

**Comment by willmkt** [comment]
Opa valeu @mja-maia, quando implementar me avisa.

Segue meu email will.mkt.cba@gmail.com

Abraços...

**Comment by willmkt** [comment]
Fala @mja-maia  alguma novidade na implementação?? 

É que ja tentei de varias formas e não da certo, ser puder ajudar estou precisando..

Valeu..

**Comment by mja-maia** [comment]
@willmkt Prontinho, feito!
